### ISSUE TITLE
mergeLonghand can break rules

### ISSUE THREAD

**Issue by ianbarker** [ben-eb/cssnano#116]
I've noticed that if mergeLonghand isn't disabled it can break some rules. E.g. `border-left-color: #999` I was using it for half coloured table cells along with spans and they were getting replaced with `border: #999` which didn't work too well.

**Comment by ben-eb** [comment]
Could you provide an input example, output and expected output please?

**Comment by s10wen** [comment]
I've just tried this and I'm seeing `border-left-color:#b51218` staying as `border-left-color:#b51218` with `mergeLonghand` set to `true`.

**Comment by joscha** [comment]
related to https://github.com/ben-eb/postcss-merge-longhand/issues/21.

**Comment by seancurtis** [comment]
When you shorten something to `border: 1px;` actually results in the browser interpreting it as `border: 1px solid transparent;`. This causes problems when you have rules afterwards which extend the border value.

Current behaviour (too generic): http://jsbin.com/bakupi/edit?html,css,output
Expected behaviour: http://jsbin.com/bakupi/edit?html,css,output

**Comment by ben-eb** [comment]
Going to consolidate tracking of this issue into https://github.com/ben-eb/postcss-merge-longhand/issues/21.
