### ISSUE TITLE
Changes in cssnano v2.0

### ISSUE THREAD

**Issue by ben-eb** [ben-eb/cssnano#15]
Here are some changes I'd like to propose for version 2:

1. Deprecate the main method and expose as a PostCSS plugin for compatibility with plugin guidelines. This is to allow people to easily consume cssnano using a PostCSS workflow, which I would like to promote over using a simple node.js workflow; simply because it makes more sense to have a pipeline of plugins such as gulp does, as parsing doesn't have to occur multiple times. I feel that plugins such as gulp-cssnano are just intended as something that you can use to swap for another minifier if you don't have some existing PostCSS pipeline, but really it is best to use the PostCSS workflow I think.

2. For those plugins though, we should expose a new `process` method which will work exactly the same as the main method currently does.

3. Remove node 0.10 compatibility - postcss-normalize-url fails tests on 0.10, and because I don't work on 0.10 anymore I would rather not have to try and include hacks for it. People on node 0.10 can still use v1.

4. Start extracting out the `lib` directory into modules. The reason for this still being there is mostly because these processors are not fully complete yet, or their functionality combines multiple actions that wouldn't make sense as a single plugin.

My plan is to finish off this selector parser for postcss-minify-selectors before anything in this list, then I can start work on the items here.

/cc @sindresorhus @MoOx @morishitter as cssnano consumers :smiley:

**Comment by MoOx** [comment]
I don't think it's a good idea to remove the simple interface.

Even if I understand your approach of encourage postcss usage directly to avoid multiple parsing/toString between tools, I don't think we should encourage most people to use postcss, because of the fragmentation of each "languages" people are creating by using some plugins.
I am going to write a blog post about that soon btw, cause I think it's a dangerous game that too many people are playing.

But maybe the `process()` can be enough.

**Comment by ben-eb** [comment]
It's tricky because the PostCSS architecture allows for many diverse opinions on CSS processing, so there are inevitably going to instances of fragmentation. I take the opposite view though, I feel empowered by using PostCSS directly as I can write modules to help me work with CSS, which I can't say for Sass as I don't know C++.

For the majority of people using cssnano in build tools this won't affect their usage of it. I just would like to expose the main module as a plugin so other plugins can access things like the PostCSS version. Similar to how the current autoprefixer API works.

Looking forward to your blog post. :smile:

@ai Do you have any thoughts on this?

**Comment by ai** [comment]
@MoOx @ben-eb I think current Autoprefixer API is nice for in-PostCSS and standalone use:

```
postcss( pack(opts) ).process(css) // in-PostCSS
pack(opts).process(css) // standalone
```

In PostCSS 4.2 I think even to add `process(css)` alias to all plugins (but you can redefine it, of course, it will not be part of API just a default shortcut).

So of course it is OK to use packs without PostCSS. Question is only about previous cssnano standalone API. I think 2.0 API with `pack(opts).process(css)` instead of `pack(css, opts)` is better and more flexible in future.

**Comment by MoOx** [comment]
> pack(opts).process(css) instead of pack(css, opts) is better and more flexible in future.

True.
I should do that for cssnext so.

**Comment by ben-eb** [comment]
A work in progress version of `2.0` is available here: https://github.com/ben-eb/cssnano/tree/2.0

**Comment by ben-eb** [comment]
Closing this. Extracting out modules will be done in patch versions.
