### ISSUE TITLE
Improvement: line-height

### ISSUE THREAD

**Issue by marcobiedermann** [ben-eb/cssnano#181]
If `line-height` has an `em` or `%` value, the unit could be removed

```
.selector {
  line-height: 1.2em;
  line-height: 120%;
}
```

is equal to
```
.selector {
  line-height: 1.2;
}
```

**Comment by ben-eb** [comment]
Is this actually the case? I'm looking at MDN's documentation for this, turns out that semantically they are different. Have a look at the section that reads 'Prefer unitless numbers for line-height values'.

https://developer.mozilla.org/en/docs/Web/CSS/line-height

Developers that are coding using this notation are probably doing themselves a disservice, but we can't adjust the value automatically as it has different semantics. I think this is better suited to a [stylelint](http://stylelint.io/) rule, so that developers can be warned before that code ends up in their CSS file, rather than it being silently transformed.
