### ISSUE TITLE
undefined [postcss-discard-empty]

### ISSUE THREAD

**Issue by lukasoppermann** [ben-eb/cssnano#212]
Hey,

so using css with gulp & postcss I always get this "warning":

```
resources/css/app.css
undefined [postcss-discard-empty]
```

If I remove cssnano, the message disappears. Am I doing something wrong? Is there any more information I can provide to help solve this issue?

**Comment by ben-eb** [comment]
Hello,

I think you are seeing the "status" messages that are being set. We introduced this change here: https://github.com/ben-eb/postcss-discard-empty/commit/c52c3c5e690e3f3dcf543de41e4c204cbb137be4.

My guess is that you have [postcss-reporter](https://github.com/postcss/postcss-reporter) installed and that is outputting these messages. Note that you can whitelist the plugins that you want to see messages from using the `plugins` option.

**Comment by mikestopcontinues** [comment]
Two things, however: 
1) This particular message is useless.
2) We'd want to see important messages from cssnano in postcss-reporter.

**Comment by ben-eb** [comment]
1. I added it because [one of our users needed this functionality](https://github.com/ben-eb/postcss-discard-empty/pull/9#issue-143547466), so it is not useless. Furthermore it is not a warning, but a *status* message. Ideally any consumer of these messages should be able to tell this by the fact that each message that is produced does not bear the `warning` type. As for the rest of the plugins, nobody has offered to contribute code that fulfils this purpose, nor asked for this functionality, so unfortunately it is low on my priority list.

2. Definitely, and this is an area in which I would like to improve, but as you can appreciate I do this project in my spare time. If you agree & think it'd be worth adding more status messages from plugins then contributions (in the same vein as https://github.com/ben-eb/postcss-discard-empty/pull/9) are most welcome.

**Comment by dalibor983** [comment]
I hove nothing against logging messages bot this message is useless just as @mikestopcontinues said.
Ok for this part of message `[postcss-discard-empty]` I now that something is discarded but what `undefined` means? What was discarded? What is line number of discarded things? ...

If `undefined` means that "postcss-discard-empty" plugin is only started but nothing has discarded than this message is ridiculous.

**Comment by ben-eb** [comment]
`undefined` is being returned because the status message that we yield here does not have a `message` property. Is there any value in adding one, given that these are status messages which are not intended to be reported but consumed by other plugins?

Like I wrote above, you should exclude postcss-discard-empty with the `plugins` option from postcss-reporter if you don't want to see these messages.

**Comment by mech** [comment]
If you using postcss-nesting which will unfortunately output empty rule as depicted here jonathantneal/postcss-nesting#19, then you will probably see this being reported.

**Comment by neocolmartin** [comment]
To give an explicit example of what was mentioned in an earlier comment:
I managed to suppress those messages by changing my `webpack.config.prod.js` file's postcss entry from this:
```js

  postcss: () => [
    // ...
    postcssReporter({
      clearMessages: true
    }),
    // ...
  ],
```
to:
```js

  postcss: () => [
    // ...
    postcssReporter({
      clearMessages: true,
      plugins: ['!postcss-discard-empty']
    }),
    // ...
  ],
```

I'm not sure if there are any other messages that postcss-discard-empty might emit that I might miss, but it certainly suppresses these ones.
