### ISSUE TITLE
Allow disabling of postcss-pseudoelements and others

### ISSUE THREAD

**Issue by jedmao** [ben-eb/cssnano#24]
Is there really no way to disable [postcss-pseudoelements](https://github.com/axa-ch/postcss-pseudoelements) and other plugins? It doesn't suggest so in the readme, far as I can tell.

**Comment by ben-eb** [comment]
For simplicity's sake, I put an option to disable processors if:

* they have some alternate mode (like stripping license comments, https://github.com/ben-eb/postcss-discard-comments)
* their functionality may be destructive in some cases (https://github.com/ben-eb/postcss-zindex)

postcss-pseudoelements doesn't fall under these categories because the optimisation both enables IE8 support of those specific pseudo-elements, and it makes the file a little bit smaller still.

Why do you need this functionality?

**Comment by jedmao** [comment]
I just have no reason to support IE8. Our minimum is IE9.

**Comment by ben-eb** [comment]
I don't understand your reasoning. At the moment there are 18 modules consumed by this module (and some to consolidate & extract out). Being able to disable them all means documenting 11 more options in both this project's readme and the command line options, plus further options as more features are added in `2.0`.

There is no benefit to disabling pseudo-elements; however there is a downside to a new user coming to this project, and finding that there are over 20 command line flags for disabling features that may not even be relevant for them.

Objectively, `a:before` is smaller than `a::before`, and works across all browsers due to their need to support backwards compatible syntax. If that should change in the future, where a vendor decides that they will not support `a:before` then I am happy to revisit this then. :smile:

**Comment by lucascono** [comment]
I believe, however, that your comment and your package imposes a way of thinking and working to other developers. In my case I do not want to support IE8 or reduce the size of the style sheet. Instead, I would like to use the correct form of pseudo-elements (`::`). Could you include the option to disable pseudo-element optimization? You do not have to understand the reasons. Some developers work with other ideas in mind.

At the moment I have been obliged to uninstall cssnano only to avoid this optimization. However, all others were good. It's really a shame to have to uninstall cssnano for its refusal to include this option.

**Comment by ben-eb** [comment]
Adding option flags increases complexity and configuration bloat, of which we have a lot of already. So far, I have not been presented with a compelling reason *to* support this behaviour. Bear in mind that this is a compression tool; it is our goal to reduce stylesheet size. Otherwise, what is the point of a compression tool?

And yes, I would like to understand the reasons behind it. I would rather drop the behaviour than provide yet another flag; but still, I have users who are on IE8 who need support.

**Comment by lucascono** [comment]
I see that you definitely do not care about the opinion of others. It is a matter of tastes and work policies.

I give you a clear example: until a few weeks ago, "cleancss" gave two options to sort the selectors, but I did not want the selectors to be sorted; Then I opened a issue to ask for an option that would disable sorting. And it only took a few days to add the option. In the comments of the issue, the author says he does not understand the motives, but since it is not something that should concern him, he added the option.

I think you are going too far in your decisions and limiting the decisions of the users of the package. You are very rigid. And when one resorts to third party packages, the most important thing should be their flexibility. But anyway, it's your package, do what you want. I will not continue to waste time with you or your package. Thank you and hope someday reconsider.

**Comment by jedmao** [comment]
@lucascono, you seem to inexplicably "want" things without a strong or valid reason as to why. Any feature request should be accompanied with a reason why; otherwise, it demands time and resources of someone who is a complete stranger to you and has no obligation to satisfy your irrational wants or make you happy.

My original feature request and reasoning behind it turned out to be weak. @ben-eb gracefully took the time to explain why this was the case. I was satisfied with his explanation and therefore withdraw my feature request. @ben-eb, I thank you for your time and consideration and appreciate all that you do for free.

That said, this is an open source repository. If you're not happy with a tiny part of it, there's no reason you can't fork it into your own slight variation without spewing disrespectful comments about how an open source developer is inherently bad because he's not willing to bend over backwards to make you happy. This attitude towards open source developers really gets under my skin. You should be grateful that they created the the tool and shared it with the world in the first place.

**Comment by lucascono** [comment]
Unfortunately I do not like whimsical people and that's why I react in this way. You are right on some points and not on others.

I greatly appreciate open source work. Almost all my developments use open source packages. However, I belong to the stream of developers who try to eradicate IE9 or earlier. So, as the developer of this package does not understand why I do not want to use a format compatible with IE8, I do not understand that the developer wants to provide such compatibility by default.

I agree more with the policy of "cleancss" or "uglifyjs", which by default no longer support IE8 or IE9. However, they provide options for compatibility with these browsers. In the case of "cleancss" is set by the option "compatibility" and in the case of "uglifyjs" with the option "screw_ie8". Another example is "autoprefixer" which by default has "> 1%, last 2 versions, Firefox ESR", and yet allows users to modify the option to be compatible with older browsers. And, soon, "bootstrap" will release its new version 4 with flexbox and without support for IE8 or IE9. And examples like these, there are many others.

You may not understand it, but these little changes are encouraging both developers and users around the world to update their obsolete browsers.

It seems to me that after so many years of supporting IE8 and IE9, it is time for all developers to promote the necessary change.

I think it's perfect if the developer of this package wants to provide compatibility with older browsers, but not by default.

Now, having explained my reasons (shared by a huge majority of developers in the world, which can be seen in the most prestigious open source projects that exist, such as those I have already mentioned), I refer next to what You call it "disrespect".

One thing is for the developer to say "I do not have time" or "Please help me to do it" (then I could collaborate with a fork / push) and another is to treat them like an idiot by saying "I do not understand their motives" when they are Too obvious.

I think currently giving IE8 / 9 support by default is to cause damage to our industry, either through an open source project or not.

That is my position. And, consequently, that is my reaction.
Best regards.

*PS: Excuse my english, my native language is spanish. All the text has been translated with the Google translator and may be misinterpreted some of the messages.*

**Comment by jedmao** [comment]
The issue with most tools that support older browsers is that they have to do something extra or add something to achieve support, so it makes total sense that you should be able to disable it.

This tool, however, does not add anything to achieve support. In fact, it removes something, making it even more concise than the alternative, all with no downside. As the author said, if any downside is presented, he will gladly adjust his position.

It's not that he doesn't care about the opinion of others, as you said; rather, he doesn't blindly do things without reason. He's doing his best to avoid building a Frankenstein and I think that's a noble goal.

BTW, Google translate did an excellent job. I thought you were native English.

**Comment by lucascono** [comment]
I take it back. Finally, reading the code of all the included plugins, I found that the transformation is originated by [postcss-minify-selectors](https://github.com/ben-eb/postcss-minify-selectors). I have already disabled it and the pseudo elements remain as I want them (as the specifications say, which is how I like it, reason more than enough).

Look, it was as simple as telling me which plugin to disable. Why ask for explanations of the reasons? Why did not it start there from the beginning?

For me, the issue can be closed.

**Comment by ben-eb** [comment]
I started developing back when IE6 was a majority browser and I remember the pain all too well. But I have to stay objective; for me, this is not a question of browser support, but of compression. cssnano's focus is to minimise CSS as much as possible, which is one of the reasons why I felt it appropriate to add in things like `calc` minimisation.

When a static `calc` value can be reduced (e.g. `calc(250px + 250px)` => `500px`), of course, the browser support is greater and legacy browsers can read the value. But this doesn't matter because the value is smaller than the original, and it reduces download time very slightly. I feel it is the same way with the single colon syntax; it is *objectively* smaller, and that's the goal of this module. That's all minification is, little tricks that take out a byte here, two bytes there.

So I do respect your goal of pushing for a more modern browser landscape, but that's not what I am doing here. I want to make CSS as small as possible, and as @jedmao says, not build a Frankenstein where I am blindly adding in option flags, and therefore not making any decisions about the direction of the module.
