### ISSUE TITLE
wish: Remove empty :not()'s

### ISSUE THREAD

**Issue by stevenvachon** [ben-eb/cssnano#251]
Could also remove empty `:matches()`

**Comment by ben-eb** [comment]
This is fairly easy to implement, would you like to send a pull request to https://github.com/ben-eb/postcss-minify-selectors? 😄

**Comment by stevenvachon** [comment]
I dunno -- I'm focusing on other side projects. I just thought that I'd report it so that it was at least mentioned somewhere.

**Comment by ben-eb** [comment]
I've had a look into this and, although it might make sense that this should make everything red, it in fact does nothing (latest Chrome):

```css
*:not() {
  color: red;
}
```

I think therefore that this is probably more suited for a linter than a compression tool. Perhaps someone at Stylelint would like to take this? 😄

**Comment by stevenvachon** [comment]
It's possible for compiled code to result in such. For example, SCSS:
```scss
$foo: "";
*:not(#{$foo}) {
  color: red;
}
```

**Comment by ben-eb** [comment]
Yeah, but if we remove the `:not()` from the selector (causing the browser to color everything `red`), the result is that we break the *production* render. I have no idea why someone would write such a selector, test it, see that it doesn't work and then keep it in their code, but if they did, wouldn't it be annoying to see that when minified the code actually behaves differently?

I'd prefer that this would be caught by a linter instead of producing a different production render to the development render; this tool isn't really for correcting broken CSS, it is for producing a smaller version of an existing stylesheet.

**Comment by stevenvachon** [comment]
You'd said in your previous comment that your code sample did *not* make text red in Chrome. Now you're saying that it does (?).

**Comment by ben-eb** [comment]
That's right, it doesn't have any effect. But if we remove the `:not()` from it, it would have the effect of making all text `red`. 😄

**Comment by stevenvachon** [comment]
Aye. Makes sense. Thank you.
