### ISSUE TITLE
merging rules breaks css

### ISSUE THREAD

**Issue by Nickman87** [ben-eb/cssnano#297]
I encountered a special case where my CSS broke after minification. I made a JSFiddle wich shows the issue:
https://jsfiddle.net/yn1ypvg9/2/
Issue is the same in Chrome, FF and IE (11)

the first block is the non minified version, the second block is the minified version.
As the "::placeholder" pseudo-selector is not recognised by the browser (because it is still experimental and only works with vendor prefixes), the entire block of css is ignored.

I'm not sure if these scenario's can be fixed because it seems to be a general way of interpreting CSS across browsers and you can write anything that is not recognised instead of 'placehoder", it will result in the same issue.

**Comment by ben-eb** [comment]
Hi @Nickman87,

Yeah, it's a tricky issue; right now cssnano is trusting the user to pass in valid selectors which it then tries to merge together. There's some logic in there that handles these cases *when they are vendor prefixed*, but not when they are specification. Seeing as the declaration is invalid in browsers right now it would be better to remove it I think, or turn off the transform `{mergeRules: false}`.

The other alternative is to maintain a list of known (pseudo) selectors, and ignore anything not on this list; I'm happy to do this but I'd prefer that this curation be done via a script, as autonomous as possible. Perhaps something that leveraged the data in https://github.com/mdn/data/blob/master/css/selectors.json would be a good addition; although right now there are a few missing vendor extensions from that list it's a start. 😄

**Comment by ncoden** [comment]
Hi @ben-eb,

We encountered this issue with at Foundation: https://github.com/zurb/foundation-sites/issues/9578. We are using autoprefixer before cssnano, so we could expect the "invalid" `::placeholder` declaration to be correctly prefixed and everything to work. But the unprefixed `::placeholder` declaration is merged with other declarations, and so break them.

So I think a list of "known invalid/unsupported" selectors would be a good idea.

**Comment by ben-eb** [comment]
@ncoden How do you think we should proceed with this? Currently, the data from MDN (https://github.com/mdn/data/blob/master/css/selectors.json) has no mention of `::placeholder`, this we can add manually for the time being, but are there other cases where the merging should be skipped?

I'll entertain the possibility of allowing users to add a list of selectors that they don't want merged together, but ideally we should do the "right" thing by default; so if we can do it autonomously that'll be the best thing as far as I'm concerned.

**Comment by ncoden** [comment]
You can do two things:
- Merge all selectors, except a list of "known invalid/unsupported" selectors with `::placeholder` in by default.
- Do not merge unknown selectors.

I think the second case is proper, because of you do not have to maintain a list of "used but not supported yet" selectors, and you prevent bug when a selector is wrongly typed.

**Comment by ben-eb** [comment]
@ai What do you think, is it a good use case for caniuse data? 😄

**Comment by ai** [comment]
Yeap, I like this idea very much. One more reason to have `browserslist` file :D.

**Comment by Nickman87** [comment]
I was looking trough the MDN repo a while ago to see how it could be used but I could not figure out how they are using it themselves as the info in the repo does not directly cross match with the MDN site.

The idea of only merging known working selectors seems like the best approach even though it will lead to slightly larger output at first. Once we figure out how the MDN repo is actually used, individual cases like this could be added as PR to their repo to improve the minification efforts so both projects will benefit from it?

**Comment by ben-eb** [comment]
I've created a pull request with an initial implementation. The idea is to automatically infer your supported browsers from the environment, using one of the [browserslist](https://github.com/ai/browserslist) configurations, instead of providing a `browsers` option. Please leave any feedback, did I miss anything? 😄

https://github.com/ben-eb/postcss-merge-rules/pull/45

**Comment by ncoden** [comment]
@ben-eb Awesome. Thank you !

**Comment by Nickman87** [comment]
@ben-eb How did you build the "pseudoElements" list? Won't it be error prone to have this list manually updated?

**Comment by ben-eb** [comment]
@Nickman87 Yeah, this will be error prone for sure, but manual curation seems to be the only way to handle this right now. It needs to be manual because we need to reference the appropriate caniuse feature for each pseudo.

It should be up to date as of when I wrote the code but will need maintenance going forward.

**Comment by Nickman87** [comment]
Maybe something that could be added to the caniuse lib to take care of this differentiation?
I don't know how it works exactly so I'm just guessing now :).

Great work though! 👍

**Comment by ben-eb** [comment]
This has now been released in postcss-merge-rules `2.1.0`.
