### ISSUE TITLE
Docs: cli install command should have --global

### ISSUE THREAD

**Issue by bfred-it** [ben-eb/cssnano#305]
http://cssnano.co/usage/#cli

The installation is shown as

```sh
npm install cssnano-cli
```

while it should be

```sh
npm install cssnano-cli --global
```

And: having those commands in `<a>` makes it impossible to copy and paste it easily.
~~And: links with fragments don't scroll to their sections, e.g. http://cssnano.co/usage/#cli~~

**Comment by ben-eb** [comment]
Not sure really, I tend to prefer local module binaries so that you can have different versions of a dependency for different projects. Keeping the dependencies self contained like this makes a project easier to set up.

Of course, you can still install it globally if you like.

It might be good to add copy to clipboard buttons for these though, using something like clipboard.js. https://clipboardjs.com

**Comment by bfred-it** [comment]
Then maybe it should be consistent on https://www.npmjs.com/package/cssnano-cli which has the --global command

**Comment by ben-eb** [comment]
Definitely, it's always good to be consistent with myself. :wink:
