### ISSUE TITLE
Upgrade the autorefixer to version 7!

### ISSUE THREAD

**Issue by retyui** [ben-eb/cssnano#365]
https://evilmartians.com/chronicles/autoprefixer-7-browserslist-2-released

**Comment by ben-eb** [comment]
Resolved in https://github.com/ben-eb/cssnano/releases/tag/v4.0.0-rc.0.

**Comment by mrmckeb** [comment]
It looks like there are still references to `autoprefixer@^6.0.0` in `cssnano-preset-advanced` - is this intentional? I've been looking into this as I've run into an issue using `browserslist` from a shared configuration file.
https://github.com/ben-eb/cssnano/blob/e94af03ccba838aa6fd5d5d353ece5bcbbd87224/packages/cssnano-preset-advanced/package.json#L15
