### ISSUE TITLE
[Question] 4.0.0-rc.2 performance drop? (vs 3.10.0)

### ISSUE THREAD

**Issue by ryanelian** [ben-eb/cssnano#399]
Hello. This is not really important but is just something that I noticed.

I tried the 4.0.0-rc.2 version of cssnano, which is apparently published a week ago (and managed to remove that annoying `Node#moveTo was deprecated. Use Container#append.` message. Nice 👍)

However, I've noticed that it performs worse in comparison to the latest stable version, which is 3.10.0.

![cssnano-time](https://user-images.githubusercontent.com/8892187/29286018-b8f92d92-815a-11e7-9830-9948ebfee58f.PNG)

The first window above is the build with cssnano 4.0.0-rc.2, which may produce output up to +1KB larger and up to 30% slower for some reason. Tested repeatedly and with another 4 projects, resulting in the same behavior.

The second window above is the build with cssnano 3.10.0.

> btw, I'm using Node 6.11.2 LTS

![cssnano-code](https://user-images.githubusercontent.com/8892187/29286020-bb177d18-815a-11e7-8b83-38053074fe4f.PNG)

^ This my code for using cssnano 4.0.0-rc.2, which follows the documentation written in http://cssnano.co/guides/presets/

To be honest, it doesn't bug me that much because ~1KB is negligible and my instapack can bypass cssnano during development using a build flag for speed.

But I can't help but to ask the reason why. Is this behavior by design or am I doing something wrong?

Thanks and keep up the good work 🌶 

EDIT: Thank you Ben for the clear and prompt explanation. I'm glad I didn't commit fully to PostCSS ecosystem but instead uses node-sass before feeding it to PostCSS for autoprefix + cssnano. I can't imagine the performance nightmare if I did otherwise. 💀

**Comment by ben-eb** [comment]
Going to link this to save repeating myself. 😄 

https://github.com/ben-eb/cssnano/issues/385#issuecomment-315087622

Regarding performance, it's not intentional but most likely a side effect of how we use PostCSS. As we add more transformations performance (read: speed, not compression) will get worse, and that's compounded by using modules like https://github.com/postcss/postcss-selector-parser - which is a fine module but it adds more work to each plugin that uses it, due to repeated parsing steps. Changing this now is a huge amount of work and not something I can realistically take on; ideally we'd be using a different parsing engine but this project is probably too invested in PostCSS to change that now.
