### ISSUE TITLE
min-width: 0 != min-width: auto

### ISSUE THREAD

**Issue by john-doherty** [ben-eb/cssnano#405]
I'm using [gulp-cssnano](https://www.npmjs.com/package/gulp-cssnano) which uses this lib under the hood and I just noticed my production app is breaking in Chrome because cssnano is replacing `min-width: auto` with `min-width: 0`.

Is there a way to disable this?

**Comment by john-doherty** [comment]
Found it, need to pass `cssNano({ postcssReduceInitial: false })`

Feels like an odd optimisation to me.

**Comment by andyjansson** [comment]
Care to share more information? What version are you running? How does it break?

**Comment by john-doherty** [comment]
It's not a version issue, replacing `min-width: initial` with `min-width: 0` in Google chrome shrinks the width of an element causing it to clip it's value.

**Comment by andyjansson** [comment]
can you provide a [minimal test case](https://codepen.io/) reproducing the issue?

>It's not a version issue 

The reason I ask is whether the behaviour is still present in newer versions, such as the new alpha.

**Comment by john-doherty** [comment]
Sure, here is a [jsfiddle](https://jsfiddle.net/cm4r0486/). Notice how the white space in `.one` is respected but ignored in `.two`.

**Comment by andyjansson** [comment]
I did some testing. Turns out it has the same behaviour even when both `<span>`s have `min-width: initial`. Your issue isn't that the minified code is somehow different from the original code, but rather that you have no text that follows the second span. 

See: 
https://jsfiddle.net/cm4r0486/6/
https://jsfiddle.net/cm4r0486/7/
