### ISSUE TITLE
Investigate css-shrink

### ISSUE THREAD

**Issue by kevinSuttle** [ben-eb/cssnano#74]
http://cssshrink.com/velocity/
https://github.com/stoyan/cssshrink has been dead for awhile, but it has a lot of useful content.

**Comment by ben-eb** [comment]
Thanks, yeah I've done some fairly extensive testing in the past, with just about every minifier available. It's been one of my aims to try and gather enough data on expected behaviour for CSS optimisations, because I found that different minifiers often produce different output. Of course, this is now also true for cssnano, but definitely parsing CSS has much more advantages than using regexes.

The test suite I was using has ~100 tests across 11 engines; some of the fixtures may need updating for cssnano's bug fixes, but is a pretty good representation of minification performance across libraries. It also needs converting to async since it still relies on the sync code in v1 of https://github.com/ben-eb/css-minifiers; but you can have a look here: https://github.com/ben-eb/css-minifier-tests.

If there's a specific case where the module is outperformed in compression and you think it should be added, it would be great if you could detail it here: https://github.com/ben-eb/cssnano/issues/46

**Comment by kevinSuttle** [comment]
Thanks @ben-eb!
